travis:
  secure:
    BINSTAR_TOKEN: fDm3rm4V0l5aLO37rmA1rRU36lyRtJKk85/fqjgOO9pY6Pbs8wAHnhYfwSQ6Dg49PQtbZkb1Lbj3byt/R/ZH5keIrrtII2PmXSIBJPbJAwVVzz5y3SOUgG22ZNravbnE72O2Z2zxD6g8HhMH4W3JtTjZ4VvZRVeq+rJx2NNPE6aYdY0GQcAtCYw+vel8EA1O4A5v7jPVOqY7fJmvnzyLjG2eFQWm61moHw9zGZiz1CgqURbvZFYIvhihzm9BcJ87QiKlggy0P7sKAwP6t34NyZZZY3P/g7TLABomA6iiKzUi4kfUOL0LPUa77hHAUQrn1oBgThNhSRYH2mL0LaOC42pYOXWiXUs7CHz1SHSJwyrfVe8u2YrSddOiVHPZaKjLO6+TRibd4D+k9eFv9PDk0loRh9k1wBGBg9fC0xPeGxm4ROrfYSTTT84zU6Q3X9Eyk5QpDH66ylAD5PfJlHxW+IgD5/q4i8hqWcGC8V41MFEGySvKKNWGOjFy6N7CS/3O32S+b28+tjs0qmlTbhiQ2iz2NG/Df2u9exzpHGCLUYiMGGT2ai61dXWQmXLMSJPjI5uS5nXpaDydUo2F0Q1QAGk46XLhoQXoXJDAhqqETt7dZMN64x7OiD2PDxWKJqu4gSbyxi+9J9THdljW9sMHiOByKxPs9Rk1x0n4Eb5gT/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
